doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        types:
          userRole: App\Application\Doctrine\Types\UserRoleType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        metadata_cache_driver:
          type: pool
          pool: doctrine.system_cache_pool
        query_cache_driver:
          type: pool
          pool: doctrine.system_cache_pool
        result_cache_driver:
          type: pool
          pool: doctrine.result_cache_pool
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: App\Domain\Entity
        controller_resolver:
            auto_mapping: false
        filters:
          is_active_filter:
            class: App\Application\Doctrine\Filters\IsActiveFilter
            enabled: true
            parameters:
              checkIsActive: true

services:
  doctrine_redis_provider:
    class: Redis
    factory: Symfony\Component\Cache\Adapter\RedisAdapter::createConnection
    arguments:
      - '%env(REDIS_DSN)%'
      - PREFIX_KEY: '%env(PROJECT_NAME)%'

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.adapter.redis
        provider: doctrine_redis_provider
      doctrine.system_cache_pool:
        adapter: cache.adapter.redis
        provider: doctrine_redis_provider

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
