old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    start_workshop:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.start_workshop', type: direct }
    delete_answer:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.delete_answer', type: direct }
  consumers:
    start_workshop:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.start_workshop', type: direct }
      queue_options: { name: 'old_sound_rabbit_mq.start_workshop' }
      callback: App\Controller\Amqp\StartWorkShop\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    delete_answer:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.delete_answer', type: direct }
      queue_options: { name: 'old_sound_rabbit_mq.delete_answer' }
      callback: App\Controller\Amqp\DeleteAnswer\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
