old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        start_workshop:
            connection:       default
            exchange_options: { name: 'old_sound_rabbit_mq.start_workshop', type: direct }
    consumers:
        task:
            connection:       default
            exchange_options: { name: 'old_sound_rabbit_mq.start_workshop', type: direct }
            queue_options:    { name: 'old_sound_rabbit_mq.start_workshop'}
            callback:         App\Consumer\TaskConsumer

