before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy_server:
  stage: deploy
  environment:
    name: server
    url: $SERVER
  script:
    - echo "$SERVER"
    - echo "$SSH_USER"
    - ssh $SSH_USER@$SERVER "sudo rm -rf /var/www/demo &&
      cd /var/www &&
      sudo mkdir /var/www/demo &&
      sudo git clone  https://github.com/pro6ka/symfony_deploy.git demo &&
      cd demo &&
      cp ~/demo/.env ./ &&
      sudo chown www-data:www-data ../demo -R &&
      sh ./deploy.sh"
    # sh ./deploy.sh $DATABASE_HOST $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME $RABBITMQ_HOST $RABBITMQ_USER $RABBITMQ_PASSWORD"
  only:
    - main
