before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - export DIR=$(date +%Y%m%d_%H%M%S)

deploy_server:
  stage: deploy
  environment:
    name: server
    url: $SERVER
  script:
    - ssh $SSH_USER@$SERVER "cd /var/www/demo &&
      sudo git clone https://github.com/pro6ka/symfony_deploy.git $DIR &&
      cd $DIR &&
      sudo cp ~/demo/.env ./ &&
      sudo chown www-data:www-data ../../demo -R &&
      sh ./deploy.sh &&
      cd ../ &&
      rm -rf /var/www/demo/$DIR/var/log &&
      sudo -u www-data ln -s /var/www/demo/shared/log /var/www/demo/$DIR/var/log &&
      ( [ ! -d /var/www/demo/current ] || mv -Tf /var/www/demo/current /var/www/demo/previous ) &&
      sudo -u www-data ln -s /var/www/demo/$DIR /var/www/demo/current"
  only:
    - main
