before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy_server:
  stage: deploy
  environment:
    name: server
    url: $SERVER
  script:
    - ssh $SSH_USER@$SERVER "sudo rm -rf /var/www/demo &&
      sudo rm -rf /etc/nginx/conf.d/demo.conf &&
      cd /var/www &&
      sudo mkdir /var/www/demo &&
      sudo git clone  https://github.com/pro6ka/symfony_deploy.git demo &&
      cd demo &&
      sudo cp ~/demo/.env ./ &&
      sudo chown www-data:www-data ../demo -R &&
      sh ./deploy.sh"
  only:
    - main
