services:

  php-fpm:
    build: docker
    container_name: ${PROJECT_NAME:-otus}_php
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME:-otus}_nginx
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15
    ports:
      - 15432:5432
    container_name: ${PROJECT_NAME:-otus}_postgresql
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'lessons_content'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./docker/data/dump:/app/dump
      - ./docker/data/postgresql:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    working_dir: /app
    hostname: rabbit-mq
    container_name: ${PROJECT_NAME:-otus}_rabbit-mq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  supervisor:
    build: docker/supervisor
    container_name: ${PRODUCT_NAME:-otus}_supervisor
    volumes:
      - ./:/app
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    working_dir: /app
    command: [ "supervisord", "-c", "/etc/supervisor/supervisord.conf" ]

  redis:
    container_name: 'redis'
    image: redis:alpine
    ports:
      - 6379:6379


volumes:
  dump:
  postgresql:
