<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240921011756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entity_id BIGINT NOT NULL, entity_type VARCHAR(255) NOT NULL, is_done BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation_user (fixation_id BIGINT NOT NULL, user_id BIGINT NOT NULL, PRIMARY KEY(fixation_id, user_id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_5522E340C769D5E1 ON fixation_user (fixation_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_5522E340A76ED395 ON fixation_user (user_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation_group (fixation_id BIGINT NOT NULL, group_id BIGINT NOT NULL, PRIMARY KEY(fixation_id, group_id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_14C44D54C769D5E1 ON fixation_group (fixation_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_14C44D54FE54D947 ON fixation_group (group_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation_revision (fixation_id BIGINT NOT NULL, revision_id BIGINT NOT NULL, PRIMARY KEY(fixation_id, revision_id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_471DB822C769D5E1 ON fixation_revision (fixation_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_471DB8221DFA7C8F ON fixation_revision (revision_id)');
        $this->addSql('ALTER TABLE fixation_user ADD CONSTRAINT fixation_user__fixation_id__fixation__id_fk FOREIGN KEY (fixation_id) REFERENCES fixation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_user ADD CONSTRAINT fixation_user__user_id__user__id_fk FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_group ADD CONSTRAINT fixation_group__fixation_id__group__id_fk FOREIGN KEY (fixation_id) REFERENCES fixation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_group ADD CONSTRAINT fixation_group__group_id__group__id_fk FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_revision ADD CONSTRAINT fixation_revision__fixation_id__fixation__id_fk FOREIGN KEY (fixation_id) REFERENCES fixation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_revision ADD CONSTRAINT fixation_revision__revision_id__revision_id_fk FOREIGN KEY (revision_id) REFERENCES revision (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fixation_user DROP CONSTRAINT IF EXISTS fixation_user__fixation_id__fixation__id_fk');
        $this->addSql('ALTER TABLE fixation_user DROP CONSTRAINT IF EXISTS fixation_user__user_id__user__id_fk');
        $this->addSql('ALTER TABLE fixation_group DROP CONSTRAINT IF EXISTS fixation_group__fixation_id__group__id_fk');
        $this->addSql('ALTER TABLE fixation_group DROP CONSTRAINT IF EXISTS fixation_group__group_id__group__id_fk');
        $this->addSql('ALTER TABLE fixation_revision DROP CONSTRAINT IF EXISTS fixation_revision__fixation_id__fixation__id_fk');
        $this->addSql('ALTER TABLE fixation_revision DROP CONSTRAINT IF EXISTS fixation_revision__revision_id__revision_id_fk');
        $this->addSql('DROP TABLE IF EXISTS fixation');
        $this->addSql('DROP TABLE IF EXISTS fixation_user');
        $this->addSql('DROP TABLE IF EXISTS fixation_group');
        $this->addSql('DROP TABLE IF EXISTS fixation_revision');
    }
}
