<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240928051548 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation_group (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_id BIGINT NOT NULL, fixation_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_14C44D54FE54D947 ON fixation_group (group_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_14C44D54C769D5E1 ON fixation_group (fixation_id)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS fixation_group__group_id__fixation_id_unique ON fixation_group (fixation_id, group_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, fixation_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_5522E340A76ED395 ON fixation_user (user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_5522E340C769D5E1 ON fixation_user (fixation_id)');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS fixation_user__user_id__fixation_id_unique ON fixation_user (fixation_id, user_id)');
        $this->addSql('ALTER TABLE fixation_group ADD CONSTRAINT fixation_group__group_id__group__id_fk FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_group ADD CONSTRAINT fixation_group__fixation_id__fixation__id_fk FOREIGN KEY (fixation_id) REFERENCES fixation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_user ADD CONSTRAINT fixation_user__user_id__user__id_fk FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_user ADD CONSTRAINT fixation_user__fixation_id__fixation__id_fk FOREIGN KEY (fixation_id) REFERENCES fixation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fixation_group DROP CONSTRAINT IF EXISTS fixation_group__group_id__group__id_fk');
        $this->addSql('ALTER TABLE fixation_group DROP CONSTRAINT IF EXISTS fixation_group__fixation_id__fixation__id_fk');
        $this->addSql('ALTER TABLE fixation_user DROP CONSTRAINT IF EXISTS fixation_user__user_id__user__id_fk');
        $this->addSql('ALTER TABLE fixation_user DROP CONSTRAINT IF EXISTS fixation_user__fixation_id__fixation__id_fk');
        $this->addSql('DROP TABLE IF EXISTS fixation_group');
        $this->addSql('DROP TABLE IF EXISTS fixation_user');
    }
}
