<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240928042321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fixation_group DROP CONSTRAINT IF EXISTS fixation_group__group_id__group__id_fk');
        $this->addSql('ALTER TABLE fixation_group DROP CONSTRAINT IF EXISTS fixation_group__fixation_id__group__id_fk');
        $this->addSql('ALTER TABLE IF EXISTS user_fixation DROP CONSTRAINT IF EXISTS user_fixation__user_id__user__id_fk');
        $this->addSql('ALTER TABLE IF EXISTS user_fixation DROP CONSTRAINT IF EXISTS user_fixation__fixation_id__fixation__id_fk');
        $this->addSql('ALTER TABLE fixation_user DROP CONSTRAINT IF EXISTS fixation_user__user_id__fixation__id_fk');
        $this->addSql('ALTER TABLE fixation_user DROP CONSTRAINT IF EXISTS fixation_user__fixation_id__fixation__id_fk');
        $this->addSql('DROP TABLE IF EXISTS fixation_group');
        $this->addSql('DROP TABLE IF EXISTS user_fixation');
        $this->addSql('DROP TABLE IF EXISTS fixation_user');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation_group (group_id BIGINT NOT NULL, fixation_id BIGINT NOT NULL, PRIMARY KEY(group_id, fixation_id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS fixation_group__fixation_id__unique ON fixation_group (fixation_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_14c44d54fe54d947 ON fixation_group (group_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS user_fixation (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT DEFAULT NULL, fixation_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_2512b661c769d5e1 ON user_fixation (fixation_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_2512b661a76ed395 ON user_fixation (user_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS fixation_user (user_id BIGINT NOT NULL, fixation_id BIGINT NOT NULL, PRIMARY KEY(user_id, fixation_id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS fixation_user__fixation_id_unique ON fixation_user (fixation_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_5522e340a76ed395 ON fixation_user (user_id)');
        $this->addSql('ALTER TABLE fixation_group ADD CONSTRAINT fixation_group__group_id__group__id_fk FOREIGN KEY (group_id) REFERENCES fixation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_group ADD CONSTRAINT fixation_group__fixation_id__group__id_fk FOREIGN KEY (fixation_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_fixation ADD CONSTRAINT user_fixation__user_id__user__id_fk FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_fixation ADD CONSTRAINT user_fixation__fixation_id__fixation__id_fk FOREIGN KEY (fixation_id) REFERENCES fixation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_user ADD CONSTRAINT fixation_user__user_id__fixation__id_fk FOREIGN KEY (user_id) REFERENCES fixation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fixation_user ADD CONSTRAINT fixation_user__fixation_id__fixation__id_fk FOREIGN KEY (fixation_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
